// file automatically generated by yaml2h.sh

static const std::string PIXPRO_WIFI_UNWRAP_PARAMS = R"(%YAML:1.0
---
unwrappedResolution: [1280, 400]
centre: [0.5, 0.524414]
inner: 0.0244141
outer: 0.5
offsetDegrees: 0
flip: false)";
