// file automatically generated by yaml2h.sh

static const std::string SEE3CAM_UNWRAP_PARAMS = R"(%YAML:1.0
---
unwrappedResolution: [1280, 400]
centre: [0.49375, 0.461111]
inner: 0.183333
outer: 0.408333
offsetDegrees: -90
flip: true)";
