// file automatically generated by yaml2h.sh

static const std::string WEBCAM360_UNWRAP_PARAMS = R"(%YAML:1.0
---
unwrappedResolution: [1280, 400]
centre: [0.454861, 0.204861]
inner: 0.0868056
outer: 0.190972
offsetDegrees: 0
flip: false)";
