#!/bin/sh

dir=`dirname "$0"`
for f in "$dir"/*.yaml; do
    noext=$(echo $f | sed 's/.yaml$//')
    basenoext=$(basename "${noext}")
    echo Writing $basenoext.h...
    echo "// file automatically generated by yaml2h.sh

static const char* ${basenoext^^}_UNWRAP_PARAMS = R\"($(cat "$f"))\";" > "$noext.h"
done
