# Below are some of the optional flags that can be set.
#
# # OpenCV is included by default; set this flag to disable
# NO_OPENCV := 1
#
# # Enables the OpenGL-based libantworld simulation environment
# WITH_LIBANTWORLD := 1
#
# # Enables libbebop to give support for Parrot Bebop drones.
# # You also need to set LIBBEBOP_PATH and the user must have ARSDK_ROOT set to
# # point to Parrot's SDK.
# WITH_LIBBEBOP := 1
#
# # Enables support for matplotlibcpp (in third_party/matplotlibcpp.h).
# # This is a simple wrapper for matplotlib, which requires python and numpy to
# # be installed. Users can optionally set PYTHON_BIN to use another version of
# # python (e.g. v2 rather than v3).
# WITH_MATPLOTLIBCPP := 1
#
# # Enables support for the i2c code. On more recent versions of Linux some of
# # the i2c headers were moved from the kernel to a userspace libi2c. This
# # (should) set the extra include/link flags as needed.
# WITH_I2C := 1

# The common BoB robotics makefile (NB: you'll want to put the correct relative
# path here)
include default.mk
