#!/bin/sh
# Script to generate a header file which includes all of the files in test_headers/

cd "$(dirname "$0")"
output=.include_test_headers.h
echo // This file was automatically generated by make_test_headers.sh > "$output"
for file in test_headers/*.h; do
    echo '#include "'$file'"' >> "$output"
done
