[tool.poetry]
name = "bob_antworld"
version = "1.0.0"
description = "A wrapper for the BoB robotics antworld module"
authors = ["Alex Dewar <a.dewar@imperial.ac.uk>"]
license = "GPL-2.0-only"
repository = "https://github.com/BrainsOnBoard/bob_robotics"
packages = [{ include="bob_robotics" }]

include = [
    { path = "bob_robotics/antworld/*.so", format = "wheel" },
    { path = "bob_robotics/antworld/*.dylib", format = "wheel" },
    { path = "bob_robotics/antworld/*.pyd", format = "wheel" },
    { path = "bob_robotics/antworld/*.dll", format = "wheel" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.23.0"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[tool.poetry.dev-dependencies]
setuptools = "^63.1.0"
scikit-build = "^0.15.0"

[build-system]
requires = ["poetry-core>=1.0.0", "scikit-build", "cmake", "ninja"]
build-backend = "poetry.core.masonry.api"
