#pragma once

// BoB robotics includes
#include "common/pose.h"

// Third-party includes
#include "third_party/path.h"
#include "third_party/units.h"

// Standard C++ includes
#include <vector>

namespace BoBRobotics {
namespace Navigation {
/**!
 *  \brief Read a set of objects (vertices) from a YAML file
 *
 * The files are of the form generated by save_object, which can be found here:
 *      https://github.com/BrainsOnBoard/vicon_marker_tools
 */
std::vector<std::vector<Length2<units::length::millimeter_t>>>
readObjects(const filesystem::path &objectFilePath);
} // Navigation
} // BoBRobotics
