#pragma once

// Third-party includes
#include "third_party/path.h"

namespace BoBRobotics {
/**!
 *  \brief Read a set of objects (vertices) from a YAML file
 *
 * The files are of the form generated by save_object, which can be found here:
 *      https://github.com/BrainsOnBoard/vicon_marker_tools
 */
auto
readObjects(const filesystem::path &objectFilePath);

} // BoBRobotics