if(UNIX)
    BoB_add_pkg_config_libraries(eigen3)
elseif(TARGET Eigen3::Eigen)
    BoB_add_link_libraries(Eigen3::Eigen)
else()
    message(FATAL_ERROR "Eigen 3 not found")
endif()

# For CMake < 3.9, we need to make the target ourselves
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    add_compile_flags(-fopenmp)
elseif(OpenMP_CXX_FOUND)
    BoB_add_link_libraries(OpenMP::OpenMP_CXX)
else()
    message(WARNING "Could not find OpenMP; Eigen will be single threaded")
endif()
