[tool.poetry]
name = "bob_navigation"
version = "1.0.0"
description = "A wrapper for the BoB robotics navigation module"
authors = ["Alex Dewar <a.dewar@imperial.ac.uk>"]
license = "GPL-2.0-only"
repository = "https://github.com/BrainsOnBoard/bob_robotics"
packages = [{ include="bob_robotics" }]

include = [
    { path = "bob_robotics/navigation/*.so", format = "wheel" },
    { path = "bob_robotics/navigation/*.dylib", format = "wheel" },
    { path = "bob_robotics/navigation/*.pyd", format = "wheel" },
    { path = "bob_robotics/navigation/*.dll", format = "wheel" },
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
matplotlib = "^3.5.2"
numpy = "^1.23.0"
pandas = "^1.4.3"
scipy = "^1.8.1"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[tool.poetry.dev-dependencies]
setuptools = "^63.1.0"
scikit-build = "^0.15.0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0", "scikit-build", "cmake", "ninja"]
build-backend = "poetry.core.masonry.api"
